package com.example.simplelector

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

data class AppStrings(
    val appTitle: String,
    val loadingLibraryPleaseWait: String,
    val sectionLibrary: String,
    val sectionReader: String,
    val sectionSettings: String,
    val themeLight: String,
    val themeDark: String,
    val themeSepia: String,
    val themeDarkSepia: String,
    val viewBooks: String,
    val viewFolders: String,
    val addFolder: String,
    val back: String,
    val close: String,
    val unknownAuthor: String,
    val unopened: String,
    val tapToRead: String,
    val searchLibraryLabel: String,
    val libraryBrowseTitle: String,
    val libraryViewLabel: String,
    val libraryPresentationLabel: String,
    val viewList: String,
    val viewCarousel: String,
    val noBooksInFolderWithFilters: String,
    val currentFolder: String,
    val browsingFolders: String,
    val foldersWord: String,
    val booksWord: String,
    val booksInCurrentFolder: String,
    val booksBelowHint: (Int) -> String,
    val jumpToBooks: String,
    val loadingLibraryTitle: String,
    val loadingLibraryMessages: List<String>,
    val emptyLibraryTitle: String,
    val emptyLibraryMessage: String,
    val selectLocation: String,
    val libraryCountsFormat: (Int, Int) -> String,
    val folderStatsFormat: (Int, Int) -> String,
    val settingsTitle: String,
    val settingsSubtitle: String,
    val libraryStatusTitle: String,
    val readingThemeTitle: String,
    val readingControlsTitle: String,
    val showPageCounter: String,
    val showPageButtons: String,
    val keepScreenOn: String,
    val lockRotationInReader: String,
    val textSizeFormat: (Int) -> String,
    val extraLineHeightFormat: (Int) -> String,
    val sideMarginFormat: (Int) -> String,
    val scannedFoldersTitle: String,
    val noFoldersAdded: String,
    val remove: String,
    val appDataTitle: String,
    val resetAppDescription: String,
    val resetAppButton: String,
    val aboutTitle: String,
    val developedBy: String,
    val versionFormat: (String) -> String,
    val githubRepository: String,
    val resetAppConfirmTitle: String,
    val resetAppConfirmMessage: String,
    val resetAppConfirmButton: String,
    val cancel: String,
    val failedImportFolder: String,
    val removedInaccessibleFolder: (Int) -> String,
    val preservedFailedFolder: (Int) -> String,
    val removedAndPreservedFolders: (Int, Int) -> String,
    val openBookFailed: String,
    val unsupportedFormatReader: String,
    val unsupportedCbrRar5Message: String,
    val bookmarkRemoved: (Int) -> String,
    val bookmarkAdded: (Int) -> String,
    val pdfZoom: String,
    val cbzZoom: String,
    val cbrZoom: String,
    val readingProgressFormat: (Int, Int, Int) -> String,
    val chaptersTitle: String,
    val bookmarksTitle: String,
    val searchTitle: String,
    val jumpToPage: String,
    val go: String,
    val previous: String,
    val next: String,
    val hide: String,
    val index: String,
    val search: String,
    val bookmarks: String,
    val bookmarked: String,
    val bookmark: String,
    val noNavigableChapters: String,
    val noBookmarksYet: String,
    val searchInBook: String,
    val searchHint: String,
    val noSearchResults: String,
    val searchResultFormat: (Int, String) -> String,
    val noBookOpen: String,
    val goToLibrary: String,
    val bookUnavailable: String,
    val chooseAnotherBook: String,
    val backToLibrary: String,
    val openingFormat: (String) -> String,
    val missingBookMessage: String,
    val bookmarkLabelFormat: (String?, String, Int) -> String,
    val rootFoldersTitle: String,
    val codeLanguagePrefix: String,
    val noReadableTextMessage: String,
    val noReadableCbzImages: String,
    val desktopChooseFolderTitle: String,
    val desktopScanApprove: String,
)

@Composable
fun rememberAppStrings(): AppStrings {
    val languageTag = currentLanguageTag()
    return remember(languageTag) { appStringsForLanguage(languageTag) }
}

fun appStrings(): AppStrings = appStringsForLanguage(currentLanguageTag())

private fun appStringsForLanguage(languageTag: String): AppStrings =
    when {
        languageTag.startsWith("es", ignoreCase = true) -> spanishStrings()
        languageTag.startsWith("ja", ignoreCase = true) -> japaneseStrings()
        languageTag.startsWith("ko", ignoreCase = true) -> koreanStrings()
        isTraditionalChinese(languageTag) -> traditionalChineseStrings()
        isSimplifiedChinese(languageTag) || languageTag.startsWith("zh", ignoreCase = true) -> simplifiedChineseStrings()
        else -> englishStrings()
    }

private fun isSimplifiedChinese(languageTag: String): Boolean {
    if (!languageTag.startsWith("zh", ignoreCase = true)) return false
    val normalized = languageTag.lowercase()
    return normalized.contains("-hans") ||
        normalized.endsWith("-cn") ||
        normalized.contains("-cn-") ||
        normalized.endsWith("-sg") ||
        normalized.contains("-sg-")
}

private fun isTraditionalChinese(languageTag: String): Boolean {
    if (!languageTag.startsWith("zh", ignoreCase = true)) return false
    val normalized = languageTag.lowercase()
    return normalized.contains("-hant") ||
        normalized.endsWith("-tw") ||
        normalized.contains("-tw-") ||
        normalized.endsWith("-hk") ||
        normalized.contains("-hk-") ||
        normalized.endsWith("-mo") ||
        normalized.contains("-mo-")
}

private fun spanishStrings(): AppStrings =
    AppStrings(
        appTitle = "Simple Lector",
        loadingLibraryPleaseWait = "Cargando biblioteca, por favor espera.",
        sectionLibrary = "Biblioteca",
        sectionReader = "Lectura",
        sectionSettings = "Ajustes",
        themeLight = "Claro",
        themeDark = "Oscuro",
        themeSepia = "Sepia",
        themeDarkSepia = "Sepia oscuro",
        viewBooks = "Libros",
        viewFolders = "Carpetas",
        addFolder = "Añadir memoria/carpeta",
        back = "Atrás",
        close = "Cerrar",
        unknownAuthor = "Autor desconocido",
        unopened = "Sin abrir",
        tapToRead = "Toca para leer",
        searchLibraryLabel = "Buscar por titulo, autor o ruta",
        libraryBrowseTitle = "Biblioteca",
        libraryViewLabel = "Contenido",
        libraryPresentationLabel = "Distribución",
        viewList = "Lista",
        viewCarousel = "Carrusel",
        noBooksInFolderWithFilters = "No hay libros en esta carpeta con los filtros actuales.",
        currentFolder = "Carpeta actual",
        browsingFolders = "Explorando carpetas",
        foldersWord = "carpetas",
        booksWord = "libros",
        booksInCurrentFolder = "Libros en esta carpeta",
        booksBelowHint = { count -> "$count libros más abajo" },
        jumpToBooks = "Ver libros",
        loadingLibraryTitle = "Actualizando biblioteca...",
        loadingLibraryMessages = listOf(
            "Revisando carpetas y actualizando libros guardados.",
            "Buscando cambios en tus archivos compatibles.",
            "Preparando biblioteca y portadas recientes.",
            "Comprobando cambios en subcarpetas y colecciones.",
            "Ordenando títulos, progreso y rutas de la biblioteca.",
            "Sincronizando portadas para mostrar resultados más rápido.",
        ),
        emptyLibraryTitle = "Tu biblioteca esta vacia",
        emptyLibraryMessage = "Añade memoria interna, SD o carpetas. Las carpetas seleccionadas adjuntaran los archivos compatibles a la biblioteca.",
        selectLocation = "Seleccionar ubicacion",
        libraryCountsFormat = { books, folders -> "$books libros en $folders carpetas" },
        folderStatsFormat = { folders, books -> "$folders carpetas · $books libros" },
        settingsTitle = "Ajustes",
        settingsSubtitle = "Carpetas, lectura y comportamiento",
        libraryStatusTitle = "Estado de biblioteca",
        readingThemeTitle = "Tema de lectura",
        readingControlsTitle = "Controles de lectura",
        showPageCounter = "Mostrar contador de paginas",
        showPageButtons = "Mostrar botones de pagina",
        keepScreenOn = "Mantener pantalla encendida",
        lockRotationInReader = "Bloquear rotacion en lectura",
        textSizeFormat = { value -> "Tamaño de texto: ${value}sp" },
        extraLineHeightFormat = { value -> "Interlineado extra: ${value}sp" },
        sideMarginFormat = { value -> "Margen lateral: ${value}dp" },
        scannedFoldersTitle = "Carpetas escaneadas",
        noFoldersAdded = "Aun no hay carpetas agregadas.",
        remove = "Quitar",
        appDataTitle = "Datos de la app",
        resetAppDescription = "Borra las carpetas escaneadas, el progreso de lectura y el ultimo libro abierto.",
        resetAppButton = "Restablecer app",
        aboutTitle = "Acerca de",
        developedBy = "Desarrollado por Lextrack Studios",
        versionFormat = { version -> "Version $version" },
        githubRepository = "Repositorio en GitHub",
        resetAppConfirmTitle = "Restablecer app",
        resetAppConfirmMessage = "Se borrarán las carpetas escaneadas, el progreso de lectura y el último libro abierto. ¿Quieres continuar?",
        resetAppConfirmButton = "Sí, borrar",
        cancel = "Cancelar",
        failedImportFolder = "No se pudo importar la carpeta seleccionada. Intenta de nuevo.",
        removedInaccessibleFolder = { count ->
            if (count == 1) "Se quitó 1 carpeta porque ya no está disponible."
            else "Se quitaron $count carpetas porque ya no están disponibles."
        },
        preservedFailedFolder = { count ->
            if (count == 1) "1 carpeta tuvo un error de escaneo. Se mantuvieron sus datos previos."
            else "$count carpetas tuvieron errores de escaneo. Se mantuvieron sus datos previos."
        },
        removedAndPreservedFolders = { inaccessible, failed ->
            buildString {
                append("Se quitaron ")
                append(inaccessible)
                append(if (inaccessible == 1) " carpeta inaccesible. " else " carpetas inaccesibles. ")
                append("Se conservaron ")
                append(failed)
                append(if (failed == 1) " carpeta con datos previos por error de escaneo." else " carpetas con datos previos por errores de escaneo.")
            }
        },
        openBookFailed = "No se pudo abrir el libro.",
        unsupportedFormatReader = "Este formato aun no tiene visor real conectado.",
        unsupportedCbrRar5Message = "Este archivo CBR usa RAR5 y todavía no es compatible. Prueba convertirlo a CBZ o a RAR4.",
        bookmarkRemoved = { page -> "Marcador quitado de la página $page" },
        bookmarkAdded = { page -> "Marcador añadido en la página $page" },
        pdfZoom = "Zoom",
        cbzZoom = "Zoom",
        cbrZoom = "Zoom",
        readingProgressFormat = { page, total, percent -> "Pagina $page de $total · $percent%" },
        chaptersTitle = "Capítulos",
        bookmarksTitle = "Marcadores",
        searchTitle = "Buscar",
        jumpToPage = "Ir a pagina",
        go = "Ir",
        previous = "Anterior",
        next = "Siguiente",
        hide = "Ocultar",
        index = "Índice",
        search = "Buscar",
        bookmarks = "Marcadores",
        bookmarked = "Marcado",
        bookmark = "Marcar",
        noNavigableChapters = "Este libro no expone capítulos navegables.",
        noBookmarksYet = "Aún no hay marcadores para este libro.",
        searchInBook = "Buscar en el libro",
        searchHint = "Escribe una palabra o frase para buscar.",
        noSearchResults = "No se encontraron coincidencias.",
        searchResultFormat = { page, preview -> "Pág. $page: $preview" },
        noBookOpen = "Ningun libro abierto",
        goToLibrary = "Ir a biblioteca",
        bookUnavailable = "Libro no disponible",
        chooseAnotherBook = "Puedes volver a la biblioteca para elegir otro libro disponible.",
        backToLibrary = "Volver a biblioteca",
        openingFormat = { format -> "Abriendo ${format.uppercase()}..." },
        missingBookMessage = "El archivo fue eliminado o cambiado de directorio. Selecciona otro para leer.",
        bookmarkLabelFormat = { chapter, title, page -> if (chapter != null) "$chapter · Pagina $page" else "$title · Pagina $page" },
        rootFoldersTitle = "Carpetas",
        codeLanguagePrefix = "Código:",
        noReadableTextMessage = "No se encontro texto legible en este archivo.",
        noReadableCbzImages = "No se encontraron imagenes legibles en este CBZ.",
        desktopChooseFolderTitle = "Selecciona una carpeta para escanear libros",
        desktopScanApprove = "Escanear",
    )

private fun englishStrings(): AppStrings =
    AppStrings(
        appTitle = "Simple Lector",
        loadingLibraryPleaseWait = "Loading library, please wait.",
        sectionLibrary = "Library",
        sectionReader = "Reader",
        sectionSettings = "Settings",
        themeLight = "Light",
        themeDark = "Dark",
        themeSepia = "Sepia",
        themeDarkSepia = "Dark sepia",
        viewBooks = "Books",
        viewFolders = "Folders",
        addFolder = "Add storage/folder",
        back = "Back",
        close = "Close",
        unknownAuthor = "Unknown author",
        unopened = "Unopened",
        tapToRead = "Tap to read",
        searchLibraryLabel = "Search by title, author, or path",
        libraryBrowseTitle = "Library",
        libraryViewLabel = "Content",
        libraryPresentationLabel = "Layout",
        viewList = "List",
        viewCarousel = "Carousel",
        noBooksInFolderWithFilters = "There are no books in this folder with the current filters.",
        currentFolder = "Current folder",
        browsingFolders = "Browsing folders",
        foldersWord = "folders",
        booksWord = "books",
        booksInCurrentFolder = "Books in this folder",
        booksBelowHint = { count -> "$count books below" },
        jumpToBooks = "View books",
        loadingLibraryTitle = "Refreshing library...",
        loadingLibraryMessages = listOf(
            "Reviewing folders and updating saved books.",
            "Looking for changes in your supported files.",
            "Preparing the library and recent covers.",
            "Checking subfolders and collections for changes.",
            "Sorting titles, progress, and library paths.",
            "Syncing covers to show results faster.",
        ),
        emptyLibraryTitle = "Your library is empty",
        emptyLibraryMessage = "Add internal storage, SD card, or folders. Selected folders will attach supported files to the library.",
        selectLocation = "Select location",
        libraryCountsFormat = { books, folders -> "$books books in $folders folders" },
        folderStatsFormat = { folders, books -> "$folders folders · $books books" },
        settingsTitle = "Settings",
        settingsSubtitle = "Folders, reading, and behavior",
        libraryStatusTitle = "Library status",
        readingThemeTitle = "Reading theme",
        readingControlsTitle = "Reading controls",
        showPageCounter = "Show page counter",
        showPageButtons = "Show page buttons",
        keepScreenOn = "Keep screen on",
        lockRotationInReader = "Lock rotation while reading",
        textSizeFormat = { value -> "Text size: ${value}sp" },
        extraLineHeightFormat = { value -> "Extra line spacing: ${value}sp" },
        sideMarginFormat = { value -> "Side margin: ${value}dp" },
        scannedFoldersTitle = "Scanned folders",
        noFoldersAdded = "No folders have been added yet.",
        remove = "Remove",
        appDataTitle = "App data",
        resetAppDescription = "Clears scanned folders, reading progress, and the last opened book.",
        resetAppButton = "Reset app",
        aboutTitle = "About",
        developedBy = "Developed by Lextrack Studios",
        versionFormat = { version -> "Version $version" },
        githubRepository = "GitHub repository",
        resetAppConfirmTitle = "Reset app",
        resetAppConfirmMessage = "Scanned folders, reading progress, and the last opened book will be deleted. Do you want to continue?",
        resetAppConfirmButton = "Yes, delete",
        cancel = "Cancel",
        failedImportFolder = "The selected folder could not be imported. Please try again.",
        removedInaccessibleFolder = { count ->
            if (count == 1) "1 folder was removed because it is no longer available."
            else "$count folders were removed because they are no longer available."
        },
        preservedFailedFolder = { count ->
            if (count == 1) "1 folder had a scan error. Its previous data was kept."
            else "$count folders had scan errors. Their previous data was kept."
        },
        removedAndPreservedFolders = { inaccessible, failed ->
            buildString {
                append(if (inaccessible == 1) "1 inaccessible folder was removed. " else "$inaccessible inaccessible folders were removed. ")
                append(if (failed == 1) "1 folder kept its previous data due to a scan error." else "$failed folders kept their previous data due to scan errors.")
            }
        },
        openBookFailed = "The book could not be opened.",
        unsupportedFormatReader = "This format does not have a real reader connected yet.",
        unsupportedCbrRar5Message = "This CBR file uses RAR5 and is not supported yet. Try converting it to CBZ or RAR4.",
        bookmarkRemoved = { page -> "Bookmark removed from page $page" },
        bookmarkAdded = { page -> "Bookmark added on page $page" },
        pdfZoom = "Zoom",
        cbzZoom = "Zoom",
        cbrZoom = "Zoom",
        readingProgressFormat = { page, total, percent -> "Page $page of $total · $percent%" },
        chaptersTitle = "Chapters",
        bookmarksTitle = "Bookmarks",
        searchTitle = "Search",
        jumpToPage = "Go to page",
        go = "Go",
        previous = "Previous",
        next = "Next",
        hide = "Hide",
        index = "Index",
        search = "Search",
        bookmarks = "Bookmarks",
        bookmarked = "Bookmarked",
        bookmark = "Bookmark",
        noNavigableChapters = "This book does not expose navigable chapters.",
        noBookmarksYet = "There are no bookmarks for this book yet.",
        searchInBook = "Search in book",
        searchHint = "Type a word or phrase to search.",
        noSearchResults = "No matches were found.",
        searchResultFormat = { page, preview -> "Pg. $page: $preview" },
        noBookOpen = "No book open",
        goToLibrary = "Go to library",
        bookUnavailable = "Book unavailable",
        chooseAnotherBook = "You can return to the library and choose another available book.",
        backToLibrary = "Back to library",
        openingFormat = { format -> "Opening ${format.uppercase()}..." },
        missingBookMessage = "The file was removed or moved. Select another one to read.",
        bookmarkLabelFormat = { chapter, title, page -> if (chapter != null) "$chapter · Page $page" else "$title · Page $page" },
        rootFoldersTitle = "Folders",
        codeLanguagePrefix = "Code:",
        noReadableTextMessage = "No readable text was found in this file.",
        noReadableCbzImages = "No readable images were found in this CBZ.",
        desktopChooseFolderTitle = "Select a folder to scan for books",
        desktopScanApprove = "Scan",
    )

private fun japaneseStrings(): AppStrings =
    AppStrings(
        appTitle = "シンプルリーダー",
        loadingLibraryPleaseWait = "ライブラリを読み込み中です。しばらくお待ちください。",
        sectionLibrary = "ライブラリ",
        sectionReader = "読書",
        sectionSettings = "設定",
        themeLight = "ライト",
        themeDark = "ダーク",
        themeSepia = "セピア",
        themeDarkSepia = "ダークセピア",
        viewBooks = "書籍",
        viewFolders = "フォルダー",
        addFolder = "ストレージ/フォルダーを追加",
        back = "戻る",
        close = "閉じる",
        unknownAuthor = "著者不明",
        unopened = "未読",
        tapToRead = "タップして読む",
        searchLibraryLabel = "タイトル、著者、またはパスで検索",
        libraryBrowseTitle = "ライブラリ",
        libraryViewLabel = "内容",
        libraryPresentationLabel = "レイアウト",
        viewList = "一覧",
        viewCarousel = "カルーセル",
        noBooksInFolderWithFilters = "現在のフィルターでは、このフォルダーに本がありません。",
        currentFolder = "現在のフォルダー",
        browsingFolders = "フォルダーを閲覧中",
        foldersWord = "フォルダー",
        booksWord = "冊",
        booksInCurrentFolder = "このフォルダーの本",
        booksBelowHint = { count -> "下に $count 冊あります" },
        jumpToBooks = "書籍を見る",
        loadingLibraryTitle = "ライブラリを更新しています...",
        loadingLibraryMessages = listOf(
            "フォルダーを確認し、保存済みの本を更新しています。",
            "対応ファイルの変更を確認しています。",
            "ライブラリと最近の表紙を準備しています。",
            "サブフォルダーやコレクションの変更を確認しています。",
            "タイトル、進捗、ライブラリのパスを整理しています。",
            "結果をすばやく表示するために表紙を同期しています。",
        ),
        emptyLibraryTitle = "ライブラリは空です",
        emptyLibraryMessage = "内部ストレージ、SD カード、またはフォルダーを追加してください。選択したフォルダー内の対応ファイルがライブラリに追加されます。",
        selectLocation = "場所を選択",
        libraryCountsFormat = { books, folders -> "$folders 個のフォルダーに $books 冊" },
        folderStatsFormat = { folders, books -> "$folders 個のフォルダー ・ $books 冊" },
        settingsTitle = "設定",
        settingsSubtitle = "フォルダー、読書、動作",
        libraryStatusTitle = "ライブラリの状態",
        readingThemeTitle = "読書テーマ",
        readingControlsTitle = "読書コントロール",
        showPageCounter = "ページカウンターを表示",
        showPageButtons = "ページボタンを表示",
        keepScreenOn = "画面をオンのままにする",
        lockRotationInReader = "読書中は画面回転を固定",
        textSizeFormat = { value -> "文字サイズ: ${value}sp" },
        extraLineHeightFormat = { value -> "追加行間: ${value}sp" },
        sideMarginFormat = { value -> "左右マージン: ${value}dp" },
        scannedFoldersTitle = "スキャン済みフォルダー",
        noFoldersAdded = "まだフォルダーは追加されていません。",
        remove = "削除",
        appDataTitle = "アプリデータ",
        resetAppDescription = "スキャン済みフォルダー、読書進捗、最後に開いた本を削除します。",
        resetAppButton = "アプリをリセット",
        aboutTitle = "このアプリについて",
        developedBy = "Lextrack Studios 開発",
        versionFormat = { version -> "バージョン $version" },
        githubRepository = "GitHub リポジトリ",
        resetAppConfirmTitle = "アプリをリセット",
        resetAppConfirmMessage = "スキャン済みフォルダー、読書進捗、最後に開いた本が削除されます。続行しますか？",
        resetAppConfirmButton = "削除する",
        cancel = "キャンセル",
        failedImportFolder = "選択したフォルダーをインポートできませんでした。もう一度お試しください。",
        removedInaccessibleFolder = { count ->
            if (count == 1) "利用できなくなったため、1 個のフォルダーを削除しました。"
            else "利用できなくなったため、$count 個のフォルダーを削除しました。"
        },
        preservedFailedFolder = { count ->
            if (count == 1) "1 個のフォルダーでスキャンエラーが発生しました。以前のデータは保持されました。"
            else "$count 個のフォルダーでスキャンエラーが発生しました。以前のデータは保持されました。"
        },
        removedAndPreservedFolders = { inaccessible, failed ->
            buildString {
                append(if (inaccessible == 1) "利用不可のフォルダーを 1 個削除しました。 " else "利用不可のフォルダーを $inaccessible 個削除しました。 ")
                append(if (failed == 1) "1 個のフォルダーはスキャンエラーのため以前のデータを保持しました。" else "$failed 個のフォルダーはスキャンエラーのため以前のデータを保持しました。")
            }
        },
        openBookFailed = "本を開けませんでした。",
        unsupportedFormatReader = "この形式にはまだ対応していません。",
        unsupportedCbrRar5Message = "この CBR ファイルは RAR5 を使用しているため、まだ対応していません。CBZ または RAR4 へ変換してください。",
        bookmarkRemoved = { page -> "$page ページのしおりを削除しました" },
        bookmarkAdded = { page -> "$page ページにしおりを追加しました" },
        pdfZoom = "ズーム",
        cbzZoom = "ズーム",
        cbrZoom = "ズーム",
        readingProgressFormat = { page, total, percent -> "$total ページ中 $page ページ ・ $percent%" },
        chaptersTitle = "章",
        bookmarksTitle = "しおり",
        searchTitle = "検索",
        jumpToPage = "ページへ移動",
        go = "移動",
        previous = "前へ",
        next = "次へ",
        hide = "非表示",
        index = "目次",
        search = "検索",
        bookmarks = "しおり",
        bookmarked = "しおり済み",
        bookmark = "しおり",
        noNavigableChapters = "この本には移動可能な章がありません。",
        noBookmarksYet = "この本にはまだしおりがありません。",
        searchInBook = "本の中を検索",
        searchHint = "検索する単語またはフレーズを入力してください。",
        noSearchResults = "一致する結果が見つかりませんでした。",
        searchResultFormat = { page, preview -> "$page ページ: $preview" },
        noBookOpen = "本が開かれていません",
        goToLibrary = "ライブラリへ",
        bookUnavailable = "この本は利用できません",
        chooseAnotherBook = "ライブラリに戻って、別の本を選択できます。",
        backToLibrary = "ライブラリに戻る",
        openingFormat = { format -> "${format.uppercase()} を開いています..." },
        missingBookMessage = "ファイルが削除されたか移動されました。読む本を別に選択してください。",
        bookmarkLabelFormat = { chapter, title, page -> if (chapter != null) "$chapter ・ $page ページ" else "$title ・ $page ページ" },
        rootFoldersTitle = "フォルダー",
        codeLanguagePrefix = "コード:",
        noReadableTextMessage = "このファイルには読み取れる本文が見つかりませんでした。",
        noReadableCbzImages = "この CBZ には読み取れる画像が見つかりませんでした。",
        desktopChooseFolderTitle = "本をスキャンするフォルダーを選択",
        desktopScanApprove = "スキャン",
    )

private fun koreanStrings(): AppStrings =
    AppStrings(
        appTitle = "심플 리더",
        loadingLibraryPleaseWait = "라이브러리를 불러오는 중입니다. 잠시만 기다려 주세요.",
        sectionLibrary = "라이브러리",
        sectionReader = "읽기",
        sectionSettings = "설정",
        themeLight = "라이트",
        themeDark = "다크",
        themeSepia = "세피아",
        themeDarkSepia = "다크 세피아",
        viewBooks = "책",
        viewFolders = "폴더",
        addFolder = "저장소 또는 폴더 추가",
        back = "뒤로",
        close = "닫기",
        unknownAuthor = "알 수 없는 저자",
        unopened = "읽지 않음",
        tapToRead = "탭해서 읽기",
        searchLibraryLabel = "제목, 저자 또는 경로로 검색",
        libraryBrowseTitle = "라이브러리",
        libraryViewLabel = "내용",
        libraryPresentationLabel = "레이아웃",
        viewList = "목록",
        viewCarousel = "캐러셀 보기",
        noBooksInFolderWithFilters = "현재 필터로는 이 폴더에 책이 없습니다.",
        currentFolder = "현재 폴더",
        browsingFolders = "폴더 탐색 중",
        foldersWord = "폴더",
        booksWord = "권",
        booksInCurrentFolder = "이 폴더의 책",
        booksBelowHint = { count -> "아래에 ${count}권 있음" },
        jumpToBooks = "책 보기",
        loadingLibraryTitle = "라이브러리 새로고침 중...",
        loadingLibraryMessages = listOf(
            "폴더를 확인하고 저장된 책을 업데이트하는 중입니다.",
            "지원되는 파일의 변경 사항을 찾는 중입니다.",
            "라이브러리와 최근 표지를 준비하는 중입니다.",
            "하위 폴더와 컬렉션의 변경 사항을 확인하는 중입니다.",
            "제목, 진행 상황, 라이브러리 경로를 정리하는 중입니다.",
            "결과를 더 빠르게 보여주기 위해 표지를 동기화하는 중입니다.",
        ),
        emptyLibraryTitle = "라이브러리가 비어 있습니다",
        emptyLibraryMessage = "내부 저장소, SD 카드 또는 폴더를 추가하세요. 선택한 폴더의 지원 파일이 라이브러리에 추가됩니다.",
        selectLocation = "위치 선택",
        libraryCountsFormat = { books, folders -> "${folders}개 폴더에 ${books}권의 책" },
        folderStatsFormat = { folders, books -> "${folders}개 폴더 · ${books}권" },
        settingsTitle = "설정",
        settingsSubtitle = "폴더, 읽기, 앱 동작",
        libraryStatusTitle = "라이브러리 상태",
        readingThemeTitle = "읽기 테마",
        readingControlsTitle = "읽기 컨트롤",
        showPageCounter = "페이지 카운터 표시",
        showPageButtons = "페이지 버튼 표시",
        keepScreenOn = "화면 켜짐 유지",
        lockRotationInReader = "읽는 동안 화면 회전 잠금",
        textSizeFormat = { value -> "텍스트 크기: ${value}sp" },
        extraLineHeightFormat = { value -> "추가 줄 간격: ${value}sp" },
        sideMarginFormat = { value -> "좌우 여백: ${value}dp" },
        scannedFoldersTitle = "스캔한 폴더",
        noFoldersAdded = "아직 추가된 폴더가 없습니다.",
        remove = "제거",
        appDataTitle = "앱 데이터",
        resetAppDescription = "스캔한 폴더, 읽기 진행 상황, 마지막으로 연 책을 지웁니다.",
        resetAppButton = "앱 초기화",
        aboutTitle = "정보",
        developedBy = "개발: Lextrack Studios",
        versionFormat = { version -> "버전 $version" },
        githubRepository = "GitHub 저장소",
        resetAppConfirmTitle = "앱 초기화",
        resetAppConfirmMessage = "스캔한 폴더, 읽기 진행 상황, 마지막으로 연 책이 삭제됩니다. 계속하시겠습니까?",
        resetAppConfirmButton = "예, 삭제",
        cancel = "취소",
        failedImportFolder = "선택한 폴더를 가져오지 못했습니다. 다시 시도해 주세요.",
        removedInaccessibleFolder = { count ->
            if (count == 1) "더 이상 사용할 수 없어 폴더 1개를 제거했습니다."
            else "더 이상 사용할 수 없어 폴더 ${count}개를 제거했습니다."
        },
        preservedFailedFolder = { count ->
            if (count == 1) "폴더 1개에서 스캔 오류가 발생했습니다. 이전 데이터는 유지되었습니다."
            else "폴더 ${count}개에서 스캔 오류가 발생했습니다. 이전 데이터는 유지되었습니다."
        },
        removedAndPreservedFolders = { inaccessible, failed ->
            buildString {
                append(if (inaccessible == 1) "접근할 수 없는 폴더 1개를 제거했습니다. " else "접근할 수 없는 폴더 ${inaccessible}개를 제거했습니다. ")
                append(if (failed == 1) "폴더 1개는 스캔 오류로 인해 이전 데이터를 유지했습니다." else "폴더 ${failed}개는 스캔 오류로 인해 이전 데이터를 유지했습니다.")
            }
        },
        openBookFailed = "책을 열 수 없습니다.",
        unsupportedFormatReader = "이 형식은 아직 읽을 수 없습니다.",
        unsupportedCbrRar5Message = "이 CBR 파일은 RAR5를 사용하므로 아직 지원되지 않습니다. CBZ 또는 RAR4로 변환해 보세요.",
        bookmarkRemoved = { page -> "${page}페이지의 책갈피를 제거했습니다" },
        bookmarkAdded = { page -> "${page}페이지에 책갈피를 추가했습니다" },
        pdfZoom = "확대/축소",
        cbzZoom = "확대/축소",
        cbrZoom = "확대/축소",
        readingProgressFormat = { page, total, percent -> "${total}페이지 중 ${page}페이지 · $percent%" },
        chaptersTitle = "챕터",
        bookmarksTitle = "책갈피",
        searchTitle = "검색",
        jumpToPage = "페이지로 이동",
        go = "이동",
        previous = "이전",
        next = "다음",
        hide = "숨기기",
        index = "목차",
        search = "검색",
        bookmarks = "책갈피",
        bookmarked = "책갈피 추가됨",
        bookmark = "책갈피",
        noNavigableChapters = "이 책에는 이동 가능한 챕터가 없습니다.",
        noBookmarksYet = "이 책에는 아직 책갈피가 없습니다.",
        searchInBook = "책에서 검색",
        searchHint = "검색할 단어 또는 문구를 입력하세요.",
        noSearchResults = "일치하는 결과를 찾지 못했습니다.",
        searchResultFormat = { page, preview -> "${page}페이지: $preview" },
        noBookOpen = "열린 책이 없습니다",
        goToLibrary = "라이브러리로 이동",
        bookUnavailable = "이 책을 열 수 없습니다",
        chooseAnotherBook = "라이브러리로 돌아가 다른 책을 선택할 수 있습니다.",
        backToLibrary = "라이브러리로 돌아가기",
        openingFormat = { format -> "${format.uppercase()} 파일을 여는 중..." },
        missingBookMessage = "파일이 삭제되었거나 이동되었습니다. 다른 책을 선택해 주세요.",
        bookmarkLabelFormat = { chapter, title, page -> if (chapter != null) "$chapter · ${page}페이지" else "$title · ${page}페이지" },
        rootFoldersTitle = "폴더",
        codeLanguagePrefix = "코드:",
        noReadableTextMessage = "이 파일에서 읽을 수 있는 텍스트를 찾지 못했습니다.",
        noReadableCbzImages = "이 CBZ에서 읽을 수 있는 이미지를 찾지 못했습니다.",
        desktopChooseFolderTitle = "책을 스캔할 폴더를 선택하세요",
        desktopScanApprove = "스캔",
    )

private fun simplifiedChineseStrings(): AppStrings =
    AppStrings(
        appTitle = "Simple Lector",
        loadingLibraryPleaseWait = "正在加载书库，请稍候。",
        sectionLibrary = "书库",
        sectionReader = "阅读",
        sectionSettings = "设置",
        themeLight = "浅色",
        themeDark = "深色",
        themeSepia = "棕褐",
        themeDarkSepia = "深色棕褐",
        viewBooks = "书籍",
        viewFolders = "文件夹",
        addFolder = "添加存储或文件夹",
        back = "返回",
        close = "关闭",
        unknownAuthor = "未知作者",
        unopened = "未打开",
        tapToRead = "点击开始阅读",
        searchLibraryLabel = "按标题、作者或路径搜索",
        libraryBrowseTitle = "书库",
        libraryViewLabel = "内容",
        libraryPresentationLabel = "布局",
        viewList = "列表",
        viewCarousel = "轮播",
        noBooksInFolderWithFilters = "当前筛选条件下，此文件夹中没有书籍。",
        currentFolder = "当前文件夹",
        browsingFolders = "正在浏览文件夹",
        foldersWord = "个文件夹",
        booksWord = "本书",
        booksInCurrentFolder = "此文件夹中的书籍",
        booksBelowHint = { count -> "下方有 $count 本书" },
        jumpToBooks = "查看书籍",
        loadingLibraryTitle = "正在刷新书库...",
        loadingLibraryMessages = listOf(
            "正在检查文件夹并更新已保存的书籍。",
            "正在查找受支持文件的变更。",
            "正在准备书库和最近的封面。",
            "正在检查子文件夹和收藏的变更。",
            "正在整理书名、进度和书库路径。",
            "正在同步封面以更快显示结果。",
        ),
        emptyLibraryTitle = "你的书库是空的",
        emptyLibraryMessage = "添加内部存储、SD 卡或文件夹。所选文件夹中的受支持文件会加入书库。",
        selectLocation = "选择位置",
        libraryCountsFormat = { books, folders -> "$folders 个文件夹中有 $books 本书" },
        folderStatsFormat = { folders, books -> "$folders 个文件夹 · $books 本书" },
        settingsTitle = "设置",
        settingsSubtitle = "文件夹、阅读与行为",
        libraryStatusTitle = "书库状态",
        readingThemeTitle = "阅读主题",
        readingControlsTitle = "阅读控制",
        showPageCounter = "显示页码计数",
        showPageButtons = "显示翻页按钮",
        keepScreenOn = "保持屏幕常亮",
        lockRotationInReader = "阅读时锁定旋转",
        textSizeFormat = { value -> "文字大小：${value}sp" },
        extraLineHeightFormat = { value -> "额外行距：${value}sp" },
        sideMarginFormat = { value -> "侧边距：${value}dp" },
        scannedFoldersTitle = "已扫描的文件夹",
        noFoldersAdded = "尚未添加任何文件夹。",
        remove = "移除",
        appDataTitle = "应用数据",
        resetAppDescription = "清除已扫描文件夹、阅读进度和上次打开的书籍。",
        resetAppButton = "重置应用",
        aboutTitle = "关于",
        developedBy = "由 Lextrack Studios 开发",
        versionFormat = { version -> "版本 $version" },
        githubRepository = "GitHub 仓库",
        resetAppConfirmTitle = "重置应用",
        resetAppConfirmMessage = "已扫描文件夹、阅读进度和上次打开的书籍将被删除。要继续吗？",
        resetAppConfirmButton = "是，删除",
        cancel = "取消",
        failedImportFolder = "无法导入所选文件夹。请重试。",
        removedInaccessibleFolder = { count ->
            if (count == 1) "已移除 1 个不可访问的文件夹。"
            else "已移除 $count 个不可访问的文件夹。"
        },
        preservedFailedFolder = { count ->
            if (count == 1) "1 个文件夹扫描出错，已保留其原有数据。"
            else "$count 个文件夹扫描出错，已保留其原有数据。"
        },
        removedAndPreservedFolders = { inaccessible, failed ->
            buildString {
                append(if (inaccessible == 1) "已移除 1 个不可访问的文件夹。 " else "已移除 $inaccessible 个不可访问的文件夹。 ")
                append(if (failed == 1) "1 个文件夹因扫描错误而保留原有数据。" else "$failed 个文件夹因扫描错误而保留原有数据。")
            }
        },
        openBookFailed = "无法打开书籍。",
        unsupportedFormatReader = "暂不支持此格式。",
        unsupportedCbrRar5Message = "此 CBR 文件使用 RAR5，暂不受支持。请尝试转换为 CBZ 或 RAR4。",
        bookmarkRemoved = { page -> "已移除第 $page 页的书签" },
        bookmarkAdded = { page -> "已在第 $page 页添加书签" },
        pdfZoom = "缩放",
        cbzZoom = "缩放",
        cbrZoom = "缩放",
        readingProgressFormat = { page, total, percent -> "第 $page / $total 页 · $percent%" },
        chaptersTitle = "章节",
        bookmarksTitle = "书签",
        searchTitle = "搜索",
        jumpToPage = "跳转页码",
        go = "前往",
        previous = "上一页",
        next = "下一页",
        hide = "隐藏",
        index = "目录",
        search = "搜索",
        bookmarks = "书签",
        bookmarked = "已加书签",
        bookmark = "添加书签",
        noNavigableChapters = "这本书没有可导航的章节。",
        noBookmarksYet = "这本书还没有书签。",
        searchInBook = "在书中搜索",
        searchHint = "输入要搜索的词语或短语。",
        noSearchResults = "未找到匹配结果。",
        searchResultFormat = { page, preview -> "第 $page 页：$preview" },
        noBookOpen = "没有打开的书",
        goToLibrary = "前往书库",
        bookUnavailable = "书籍不可用",
        chooseAnotherBook = "可返回书库，选择另一本可用书籍。",
        backToLibrary = "返回书库",
        openingFormat = { format -> "正在打开 ${format.uppercase()}..." },
        missingBookMessage = "文件已被删除或移动。请选择其他书籍继续阅读。",
        bookmarkLabelFormat = { chapter, title, page -> if (chapter != null) "$chapter · 第 $page 页" else "$title · 第 $page 页" },
        rootFoldersTitle = "文件夹",
        codeLanguagePrefix = "代码：",
        noReadableTextMessage = "此文件中未找到可阅读的文本。",
        noReadableCbzImages = "此 CBZ 中未找到可显示的图片。",
        desktopChooseFolderTitle = "选择要扫描书籍的文件夹",
        desktopScanApprove = "扫描",
    )

private fun traditionalChineseStrings(): AppStrings =
    AppStrings(
        appTitle = "Simple Lector",
        loadingLibraryPleaseWait = "正在載入書庫，請稍候。",
        sectionLibrary = "書庫",
        sectionReader = "閱讀",
        sectionSettings = "設定",
        themeLight = "淺色",
        themeDark = "深色",
        themeSepia = "棕褐",
        themeDarkSepia = "深色棕褐",
        viewBooks = "書籍",
        viewFolders = "資料夾",
        addFolder = "新增儲存空間或資料夾",
        back = "返回",
        close = "關閉",
        unknownAuthor = "未知作者",
        unopened = "未開啟",
        tapToRead = "點一下開始閱讀",
        searchLibraryLabel = "依標題、作者或路徑搜尋",
        libraryBrowseTitle = "書庫",
        libraryViewLabel = "內容",
        libraryPresentationLabel = "版面",
        viewList = "列表",
        viewCarousel = "輪播",
        noBooksInFolderWithFilters = "目前篩選條件下，此資料夾中沒有書籍。",
        currentFolder = "目前資料夾",
        browsingFolders = "正在瀏覽資料夾",
        foldersWord = "個資料夾",
        booksWord = "本書",
        booksInCurrentFolder = "此資料夾中的書籍",
        booksBelowHint = { count -> "下方有 $count 本書" },
        jumpToBooks = "查看書籍",
        loadingLibraryTitle = "正在重新整理書庫...",
        loadingLibraryMessages = listOf(
            "正在檢查資料夾並更新已儲存的書籍。",
            "正在尋找支援檔案的變更。",
            "正在準備書庫與最近的封面。",
            "正在檢查子資料夾與收藏的變更。",
            "正在整理書名、進度與書庫路徑。",
            "正在同步封面以更快顯示結果。",
        ),
        emptyLibraryTitle = "你的書庫是空的",
        emptyLibraryMessage = "新增內部儲存空間、SD 卡或資料夾。所選資料夾中的支援檔案會加入書庫。",
        selectLocation = "選擇位置",
        libraryCountsFormat = { books, folders -> "$folders 個資料夾中有 $books 本書" },
        folderStatsFormat = { folders, books -> "$folders 個資料夾 · $books 本書" },
        settingsTitle = "設定",
        settingsSubtitle = "資料夾、閱讀與行為",
        libraryStatusTitle = "書庫狀態",
        readingThemeTitle = "閱讀主題",
        readingControlsTitle = "閱讀控制",
        showPageCounter = "顯示頁碼計數",
        showPageButtons = "顯示翻頁按鈕",
        keepScreenOn = "保持螢幕常亮",
        lockRotationInReader = "閱讀時鎖定旋轉",
        textSizeFormat = { value -> "文字大小：${value}sp" },
        extraLineHeightFormat = { value -> "額外行距：${value}sp" },
        sideMarginFormat = { value -> "側邊距：${value}dp" },
        scannedFoldersTitle = "已掃描的資料夾",
        noFoldersAdded = "尚未新增任何資料夾。",
        remove = "移除",
        appDataTitle = "應用程式資料",
        resetAppDescription = "清除已掃描資料夾、閱讀進度與上次開啟的書籍。",
        resetAppButton = "重設應用程式",
        aboutTitle = "關於",
        developedBy = "由 Lextrack Studios 開發",
        versionFormat = { version -> "版本 $version" },
        githubRepository = "GitHub 儲存庫",
        resetAppConfirmTitle = "重設應用程式",
        resetAppConfirmMessage = "已掃描資料夾、閱讀進度與上次開啟的書籍將被刪除。要繼續嗎？",
        resetAppConfirmButton = "是，刪除",
        cancel = "取消",
        failedImportFolder = "無法匯入所選資料夾。請再試一次。",
        removedInaccessibleFolder = { count ->
            if (count == 1) "已移除 1 個無法存取的資料夾。"
            else "已移除 $count 個無法存取的資料夾。"
        },
        preservedFailedFolder = { count ->
            if (count == 1) "1 個資料夾掃描失敗，已保留原有資料。"
            else "$count 個資料夾掃描失敗，已保留原有資料。"
        },
        removedAndPreservedFolders = { inaccessible, failed ->
            buildString {
                append(if (inaccessible == 1) "已移除 1 個無法存取的資料夾。 " else "已移除 $inaccessible 個無法存取的資料夾。 ")
                append(if (failed == 1) "1 個資料夾因掃描錯誤而保留原有資料。" else "$failed 個資料夾因掃描錯誤而保留原有資料。")
            }
        },
        openBookFailed = "無法開啟書籍。",
        unsupportedFormatReader = "暫不支援此格式。",
        unsupportedCbrRar5Message = "此 CBR 檔案使用 RAR5，尚未支援。請嘗試轉換為 CBZ 或 RAR4。",
        bookmarkRemoved = { page -> "已移除第 $page 頁的書籤" },
        bookmarkAdded = { page -> "已在第 $page 頁新增書籤" },
        pdfZoom = "縮放",
        cbzZoom = "縮放",
        cbrZoom = "縮放",
        readingProgressFormat = { page, total, percent -> "第 $page / $total 頁 · $percent%" },
        chaptersTitle = "章節",
        bookmarksTitle = "書籤",
        searchTitle = "搜尋",
        jumpToPage = "跳至頁碼",
        go = "前往",
        previous = "上一頁",
        next = "下一頁",
        hide = "隱藏",
        index = "目錄",
        search = "搜尋",
        bookmarks = "書籤",
        bookmarked = "已加書籤",
        bookmark = "新增書籤",
        noNavigableChapters = "這本書沒有可導覽的章節。",
        noBookmarksYet = "這本書還沒有書籤。",
        searchInBook = "在書中搜尋",
        searchHint = "輸入要搜尋的字詞或片語。",
        noSearchResults = "找不到符合的結果。",
        searchResultFormat = { page, preview -> "第 $page 頁：$preview" },
        noBookOpen = "沒有開啟的書",
        goToLibrary = "前往書庫",
        bookUnavailable = "書籍不可用",
        chooseAnotherBook = "可返回書庫，選擇另一本可用書籍。",
        backToLibrary = "返回書庫",
        openingFormat = { format -> "正在開啟 ${format.uppercase()}..." },
        missingBookMessage = "檔案已被刪除或移動。請選擇其他書籍繼續閱讀。",
        bookmarkLabelFormat = { chapter, title, page -> if (chapter != null) "$chapter · 第 $page 頁" else "$title · 第 $page 頁" },
        rootFoldersTitle = "資料夾",
        codeLanguagePrefix = "程式碼：",
        noReadableTextMessage = "此檔案中找不到可閱讀的文字。",
        noReadableCbzImages = "此 CBZ 中找不到可顯示的影像。",
        desktopChooseFolderTitle = "選擇要掃描書籍的資料夾",
        desktopScanApprove = "掃描",
    )

fun AppSection.localizedLabel(strings: AppStrings): String = when (this) {
    AppSection.Library -> strings.sectionLibrary
    AppSection.Reader -> strings.sectionReader
    AppSection.Settings -> strings.sectionSettings
}

fun ReaderTheme.localizedLabel(strings: AppStrings): String = when (this) {
    ReaderTheme.Light -> strings.themeLight
    ReaderTheme.Dark -> strings.themeDark
    ReaderTheme.Sepia -> strings.themeSepia
    ReaderTheme.DarkSepia -> strings.themeDarkSepia
}

fun LibraryViewMode.localizedLabel(strings: AppStrings): String = when (this) {
    LibraryViewMode.Books -> strings.viewBooks
    LibraryViewMode.Folders -> strings.viewFolders
}

fun LibraryPresentationMode.localizedLabel(strings: AppStrings): String = when (this) {
    LibraryPresentationMode.List -> strings.viewList
    LibraryPresentationMode.Carousel -> strings.viewCarousel
}
